import time
from typing import Dict, Any, List
from app.config import settings
from app.schemas.schemas import Severity, RiskLevel

def process_event(session_id: str, event: Dict[str, Any], session: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Ingests a proctoring event and decides if a flag should be raised.
    Returns a list of flags generated by this event. Mutates `session`.
    """
    event_type = event.get("event_type")
    timestamp = event.get("timestamp", time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))
    duration_ms = event.get("duration_ms", 0.0)
    confidence = event.get("confidence", 1.0)
    
    new_flags = []
    
    # 1. State machine rules / Identity Check
    if event_type == "id_verified":
        session["id_check"] = "id_verified"
        return []
    elif event_type == "id_failed":
        session["id_check"] = "id_failed"
        # Add high-severity identity flag
        flag = {
            "type": "id_failed",
            "timestamp": timestamp,
            "severity": Severity.HIGH,
            "duration_ms": 0.0
        }
        session["flags"].append(flag)
        return [flag]

    # 2. Time-duration threshold checks
    if event_type == "gaze_off_screen":
        threshold_ms = settings.gaze_off_screen_threshold_sec * 1000.0
        if duration_ms >= threshold_ms:
            severity = Severity.LOW
            if duration_ms > 8000.0:
                severity = Severity.MEDIUM
            if duration_ms > 15000.0:
                severity = Severity.HIGH
                
            flag = {
                "type": "gaze_off_screen",
                "timestamp": timestamp,
                "severity": severity,
                "duration_ms": duration_ms
            }
            session["flags"].append(flag)
            new_flags.append(flag)

    elif event_type == "face_not_detected":
        threshold_ms = settings.face_not_detected_threshold_sec * 1000.0
        if duration_ms >= threshold_ms:
            severity = Severity.LOW
            if duration_ms > 10000.0:
                severity = Severity.MEDIUM
            if duration_ms > 20000.0:
                severity = Severity.HIGH
                
            flag = {
                "type": "face_not_detected",
                "timestamp": timestamp,
                "severity": severity,
                "duration_ms": duration_ms
            }
            session["flags"].append(flag)
            new_flags.append(flag)

    # 3. Instant trigger checks (any occurrence is flagged)
    elif event_type == "tab_switched":
        flag = {
            "type": "tab_switched",
            "timestamp": timestamp,
            "severity": Severity.MEDIUM,
            "duration_ms": 0.0
        }
        session["flags"].append(flag)
        new_flags.append(flag)

    elif event_type == "fullscreen_exited":
        flag = {
            "type": "fullscreen_exited",
            "timestamp": timestamp,
            "severity": Severity.MEDIUM,
            "duration_ms": 0.0
        }
        session["flags"].append(flag)
        new_flags.append(flag)

    elif event_type == "multiple_faces_detected":
        flag = {
            "type": "multiple_faces_detected",
            "timestamp": timestamp,
            "severity": Severity.HIGH,
            "duration_ms": 0.0
        }
        session["flags"].append(flag)
        new_flags.append(flag)

    elif event_type == "paste_attempted":
        flag = {
            "type": "paste_attempted",
            "timestamp": timestamp,
            "severity": Severity.LOW,
            "duration_ms": 0.0
        }
        session["flags"].append(flag)
        new_flags.append(flag)

    elif event_type == "user_inactive":
        flag = {
            "type": "user_inactive",
            "timestamp": timestamp,
            "severity": Severity.MEDIUM,
            "duration_ms": duration_ms
        }
        session["flags"].append(flag)
        new_flags.append(flag)

    elif event_type == "screenshot_detected":
        flag = {
            "type": "screenshot_detected",
            "timestamp": timestamp,
            "severity": Severity.HIGH,
            "duration_ms": 0.0
        }
        session["flags"].append(flag)
        new_flags.append(flag)

    elif event_type == "speaking_detected":
        # Sustained audio/voice activity during exam — outside assistance risk
        flag = {
            "type": "speaking_detected",
            "timestamp": timestamp,
            "severity": Severity.HIGH,
            "duration_ms": duration_ms
        }
        session["flags"].append(flag)
        new_flags.append(flag)

    # Append raw event
    session["events"].append(event)
    session["last_event_at"] = time.time()
    
    return new_flags

def finalize_proctoring_report(session_id: str, session: Dict[str, Any]) -> Dict[str, Any]:
    """
    Computes final integrity score, risk level, summarizes flag counts,
    and returns the structured proctoring report.
    """
    now = time.time()
    
    # Check for connection lost (silence detector)
    last_active = session["last_event_at"]
    time_since_last_event = now - last_active
    
    # If the session wasn't already ended and has been silent for too long
    if not session.get("is_ended") and time_since_last_event > settings.connection_lost_timeout_sec:
        # Inject connection lost flag
        flag = {
            "type": "connection_lost",
            "timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(last_active)),
            "severity": Severity.HIGH,
            "duration_ms": time_since_last_event * 1000.0
        }
        session["flags"].append(flag)
        session["id_check"] = "id_failed" # Automatically fail clean verification if connection was dropped completely

    flags = session["flags"]
    
    # 1. Compute Integrity Score
    score = 1.0
    
    penalty_map = {
        "gaze_off_screen": settings.gaze_off_screen_penalty,
        "multiple_faces_detected": settings.multiple_faces_penalty,
        "face_not_detected": settings.face_not_detected_penalty,
        "tab_switched": settings.tab_switched_penalty,
        "fullscreen_exited": settings.fullscreen_exited_penalty,
        "paste_attempted": settings.paste_attempted_penalty,
        "screenshot_detected": settings.screenshot_detected_penalty,
        "connection_lost": settings.connection_lost_penalty,
        "speaking_detected": 0.15,  # High risk — talking during exam
        "user_inactive": 0.05,

        "id_failed": 0.5
    }
    
    flag_summary = {
        "gaze_off_screen": 0,
        "multiple_faces_detected": 0,
        "face_not_detected": 0,
        "tab_switched": 0,
        "fullscreen_exited": 0,
        "paste_attempted": 0,
        "screenshot_detected": 0,
        "speaking_detected": 0,
        "connection_lost": 0,
        "user_inactive": 0
    }
    
    for flag in flags:
        ftype = flag["type"]
        penalty = penalty_map.get(ftype, 0.05)
        
        # Scale penalty slightly for high severity duration-based flags
        if flag["severity"] == Severity.HIGH:
            penalty *= 1.5
            
        score -= penalty
        if ftype in flag_summary:
            flag_summary[ftype] += 1
            
    # Clamp score
    score = max(0.0, min(1.0, round(score, 2)))
    
    # 2. Risk Level bucket
    if score >= 0.80:
        risk_level = RiskLevel.LOW
    elif score >= 0.50:
        risk_level = RiskLevel.MEDIUM
    else:
        risk_level = RiskLevel.HIGH
        
    # Overwrite risk if identity verification failed
    if session["id_check"] == "id_failed":
        risk_level = RiskLevel.HIGH
        score = min(score, 0.4)

    # 3. Narrative explanation
    narrative_parts = []
    if session["id_check"] == "id_verified":
        narrative_parts.append("Student identity was verified successfully at start.")
    elif session["id_check"] == "id_failed":
        narrative_parts.append("Identity verification failed or was not completed.")
        
    if len(flags) == 0:
        narrative_parts.append("The student remained fully on-screen and attentive throughout the session with zero flags.")
    else:
        gaze_count = flag_summary.get("gaze_off_screen", 0)
        tab_count = flag_summary.get("tab_switched", 0)
        face_lost = flag_summary.get("face_not_detected", 0)
        conn_lost = flag_summary.get("connection_lost", 0)
        
        if gaze_count > 0:
            narrative_parts.append(f"Gaze shifted off-screen or head turned {gaze_count} times.")
        if tab_count > 0:
            narrative_parts.append(f"Student left the active browser window/tab {tab_count} times.")
        if face_lost > 0:
            narrative_parts.append(f"Face was not detected in the frame for a total of {face_lost} periods.")
        if conn_lost > 0:
            narrative_parts.append("The viva session experienced connection loss or dropped camera feed.")
        speaking_count = flag_summary.get("speaking_detected", 0)
        if speaking_count > 0:
            narrative_parts.append(f"Voice/audio activity detected {speaking_count} times suggesting possible outside communication.")
        inactive_count = flag_summary.get("user_inactive", 0)
        if inactive_count > 0:
            narrative_parts.append(f"Student was completely inactive during questioning {inactive_count} times.")

        if risk_level == RiskLevel.LOW:
            narrative_parts.append("Attentiveness was overall satisfactory with negligible deviations.")
        elif risk_level == RiskLevel.MEDIUM:
            narrative_parts.append("Attentiveness showed moderate deviations. Mentor review is advised.")
        else:
            narrative_parts.append("Significant integrity flags detected. High risk of outside assistance.")
            
    narrative = " ".join(narrative_parts)
    
    report = {
        "session_id": session_id,
        "id_check": session["id_check"],
        "integrity_score": score,
        "risk_level": risk_level,
        "flag_summary": flag_summary,
        "flags": flags,
        "narrative": narrative
    }
    
    session["is_ended"] = True
    session["proctoring_report"] = report
    
    return report
